# all the files will be generated with this name (main.elf, main.bin, main.hex, etc)
PROJ_NAME=Kauil_STM32

# Location of the files required for the linux build system
LINUXWORKSPACE = LinuxWorkspace

# Location of all the files generated by the compiler (Right now we use Keil's default)
OUTDIR = Output

# Location of the linker scripts
LDSCRIPT_INC = $(LINUXWORKSPACE)/ldscripts

# Location of OpenOCD Board .cfg files (only used with 'make program')
OPENOCD_BOARD_DIR=/usr/local/share/openocd/scripts/board

# Configuration (cfg) file containing programming directives for OpenOCD
OPENOCD_PROC_FILE=openOCD_flash.cfg

CC=arm-none-eabi-gcc
GDB=arm-none-eabi-gdb
OBJCOPY=arm-none-eabi-objcopy
OBJDUMP=arm-none-eabi-objdump
SIZE=arm-none-eabi-size

CFLAGS  = -Wall -g -std=c99 -O0  
CFLAGS += -mlittle-endian -mcpu=cortex-m4  -march=armv7e-m -mthumb
CFLAGS += -mfpu=fpv4-sp-d16 -mfloat-abi=hard
CFLAGS += -ffunction-sections -fdata-sections

LDFLAGS += -Wl,--gc-sections -Wl,-Map=$(OUTDIR)/$(PROJ_NAME).map

# Manually add specific folders as include paths
CFLAGS += -I Source/STM32_USB-FS-Device_Driver/inc
CFLAGS += -I Source/CMSIS/Include
CFLAGS += -I Source/CMSIS/Device/ST/STM32F30x/Include
CFLAGS += -I Source/STM32F30x_StdPeriph_Driver/inc
CFLAGS += -include Source/stm32f30x_conf.h

# Adds every folder in the Source/ directory as an include path
CFLAGS += $(addprefix -I , $(shell find Source -maxdepth 1 -type d))

STARTUP = $(LINUXWORKSPACE)/startup_stm32f30x.s # add startup file to build

# Finds all .c files in the source directory to compile them, and create 
# their respective .o and .d files
SOURCES = $(shell find Source -name "*.c")
OBJECTS = $(addprefix $(OUTDIR)/, $(notdir $(patsubst %.c, %.o, $(SOURCES))))
DEPS = $(addprefix $(OUTDIR)/,$(SOURCES:.c=.d))

VPATH = $(shell find Source -type d)

# Recipies

.PHONY: all proj program debug clean reallyclean

all: proj

-include $(DEPS)

proj: 	$(PROJ_NAME).elf

depend : $(OBJECTS)

$(OUTDIR)/%.o: %.c
	mkdir -p $(OUTDIR)
	$(CC) $(CFLAGS) -c -o $@ $< -MMD 
	
$(PROJ_NAME).elf: $(OBJECTS)
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $(OUTDIR)/$(@F) $(STARTUP) -L$(LDSCRIPT_INC) -Tstm32f3.ld -gstabs
	$(OBJCOPY) -O ihex $(OUTDIR)/$(PROJ_NAME).elf $(OUTDIR)/$(PROJ_NAME).hex
	$(OBJCOPY) -O binary $(OUTDIR)/$(PROJ_NAME).elf $(OUTDIR)/$(PROJ_NAME).bin
	$(OBJDUMP) -St $(OUTDIR)/$(PROJ_NAME).elf >$(OUTDIR)/$(PROJ_NAME).lst
	$(SIZE) $(OUTDIR)/$(PROJ_NAME).elf

program: all
	openocd -f $(OPENOCD_BOARD_DIR)/stm32f3discovery.cfg -f $(LINUXWORKSPACE)/$(OPENOCD_PROC_FILE) -c "stm_flash `pwd`/$(OUTDIR)/$(PROJ_NAME).bin" -c shutdown

debug: program
	$(GDB) -x $(LINUXWORKSPACE)/gdb_startup_cmds $(OUTDIR)/$(PROJ_NAME).elf

erase: 
	openocd -f /usr/local/share/openocd/scripts/board/stm32f3discovery.cfg -f $(LINUXWORKSPACE)/$(OPENOCD_PROC_FILE) -c "stm_erase" -c shutdown

clean:
	find ./ -name '*~' | xargs rm -f	
	rm -f $(OUTDIR)/*.o
	rm -f $(OUTDIR)/*.d
	rm -f $(OUTDIR)/$(PROJ_NAME).elf
	rm -f $(OUTDIR)/$(PROJ_NAME).hex
	rm -f $(OUTDIR)/$(PROJ_NAME).bin
	rm -f $(OUTDIR)/$(PROJ_NAME).map
	rm -f $(OUTDIR)/$(PROJ_NAME).lst

